---
groups:
  - name: cpi-ruby
    jobs:
      - unit-tests
      - publish-major
      - publish-minor
      - publish-patch

shared:
  - &failure-alert
    put: slack-alert
    params:
      silent: true
      channel: {{slack_channel_name}}
      icon_emoji: ":interrobang:"
      text: |
        *The <$ATC_EXTERNAL_URL/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME / $BUILD_JOB_NAME> job failed!*
  - &success-alert
    put: slack-alert
    params:
      silent: true
      channel: {{slack_channel_name}}
      icon_emoji: ":rocket:"
      text: |
        *The <$ATC_EXTERNAL_URL/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME / $BUILD_JOB_NAME> job passed!*

jobs:
  - name: unit-tests
    public: true
    serial: true
    build_logs_to_retain: 250
    plan:
      - { get: bosh-src, trigger: true }
      - task: test
        file: bosh-src/ci/tasks/test-unit.yml
        on_failure: *failure-alert

  - name: publish-minor
    public: true
    serial: true
    plan:
      - get: bosh-src
        passed: [unit-tests]
        trigger: false
      - get: version-semver
        params: { bump: minor }
      - &publish
        do:
        - task: publish
          file: bosh-src/ci/tasks/publish-gem.yml
          params:
            RUBYGEMS_API_KEY: {{rubygems_api_key}}
        - put: version-semver
          params: { file: version-semver/number }
        on_success: *success-alert
        on_failure: *failure-alert

  - name: publish-major
    public: true
    serial: true
    plan:
      - get: bosh-src
        passed: [unit-tests]
        trigger: false
      - get: version-semver
        params: { bump: major }
      - *publish

  - name: publish-patch
    public: true
    serial: true
    plan:
      - get: bosh-src
        passed: [unit-tests]
        trigger: false
      - get: version-semver
        params: { bump: patch }
      - *publish

resources:
  - name: bosh-src
    type: git
    source:
      uri: {{bosh_cpi_url}}
      branch: master

  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack_hook_url}}

  - name: version-semver
    type: semver
    source:
      key: current-version
      access_key_id: {{bosh_cpi_ruby__access_key}}
      secret_access_key: {{bosh_cpi_ruby__secret_key}}
      bucket: {{bosh_cpi_ruby__bucket}}
