---
groups:
  - name: cpi-ruby
    jobs:
      - unit-tests

jobs:
  - name: unit-tests
    public: true
    serial: true
    build_logs_to_retain: 250
    plan:
      - { get: bosh-src, trigger: true }

      - task: test
        file: bosh-src/ci/tasks/test-unit.yml
        on_failure:
          put: slack-alert
          params:
            channel: {{slack_channel_name}}
            icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
            text: {{slack_failure_message}}

resources:
  - name: bosh-src
    type: git
    source:
      uri: {{bosh_cpi_url}}
      branch: master
      private_key: {{github_deployment_key}}

  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack_hook_url}}
